version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"     # RabbitMQ Port
      - "15672:15672"   # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    
  orderservice:
    build:
      context: .
      dockerfile: BookOrderingSystem.OrderService/Dockerfile
    container_name: orderservice
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - RabbitMQ__Host=rabbitmq
    stdin_open: true    # Für Console.ReadLine()
    tty: true          # Für interaktive Console
    
  billingservice:
    build:
      context: .
      dockerfile: BookOrderingSystem.BillingService/Dockerfile
    container_name: billingservice
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - RabbitMQ__Host=rabbitmq
    
  notificationservice:
    build:
      context: .
      dockerfile: BookOrderingSystem.NotificationService/Dockerfile
    container_name: notificationservice
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - RabbitMQ__Host=rabbitmq